services:

  backend:
    build:
      context: ./backend
    env_file:
      - .env
    expose:
      - "5000"
    volumes:
      - ./volumes/data:/app/data
      - ./volumes/uploads:/app/uploads
      - ./volumes/verified:/app/verified
      - ./volumes/origin:/app/origin
      - ./volumes/resources:/app/resources
      - ./volumes/accountGen:/app/accountGen
    command: pnpm start
    networks:
      - exam_sys
  frontend:
    build:
      context: ./frontend
    env_file:
      - .env
    expose:
      - "3000"
    depends_on:
      - backend
    command: pnpm start
    networks:
      - exam_sys
  cloudflared:
    image: cloudflare/cloudflared
    env_file:
      - .env
    command: tunnel run --no-autoupdate --token ${CLOUDFLARED_TOKEN}
    depends_on:
      - backend
      - frontend
    networks:
      - exam_sys
  networks:
    exam_sys:
      driver: bridge