services:

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env.backend
    expose:
      - "80"
    volumes:
      - ./volumes/data:/app/data
      - ./volumes/uploads:/app/uploads
      - ./volumes/verified:/app/verified
      - ./volumes/origin:/app/origin
      - ./volumes/resources:/app/resources
      - ./volumes/accountGen:/app/accountGen
    command: pnpm start
    networks:
      - exam_sys
  frontend:
    build:
      context: ./frontend
    expose:
      - "80"
    depends_on:
      - backend
    networks:
      - exam_sys
  https-nginx:
    image: nginx:latest
    expose:
      - "443"
    volumes:
      - ./nginx-https/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-https/cf-origin.pem:/etc/nginx/ssl/cf-origin.pem:ro
      - ./nginx-https/cf-origin.key:/etc/nginx/ssl/cf-origin.key:ro
    depends_on:
      - frontend
      - backend
    networks:
      - exam_sys
  cloudflared:
    image: cloudflare/cloudflared:latest
    env_file:
      - .env
    command: tunnel run --token ${TUNNEL_TOKEN}
    depends_on:
      - backend
      - frontend
      - https-nginx
    networks:
      - exam_sys
networks:
  exam_sys:
    driver: bridge